// flow-typed signature: 0bb625735e20d7962ae49c30fdb7716a
// flow-typed version: <<STUB>>/@fortawesome/fontawesome-free_v^5.3.1/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/fontawesome-free'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/fontawesome-free' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fortawesome/fontawesome-free/js/all' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free/js/all.min' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free/js/brands' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free/js/brands.min' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free/js/conflict-detection' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free/js/conflict-detection.min' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free/js/fontawesome' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free/js/fontawesome.min' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free/js/regular' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free/js/regular.min' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free/js/solid' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free/js/solid.min' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free/js/v4-shims' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free/js/v4-shims.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fortawesome/fontawesome-free/js/all.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free/js/all'>;
}
declare module '@fortawesome/fontawesome-free/js/all.min.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free/js/all.min'>;
}
declare module '@fortawesome/fontawesome-free/js/brands.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free/js/brands'>;
}
declare module '@fortawesome/fontawesome-free/js/brands.min.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free/js/brands.min'>;
}
declare module '@fortawesome/fontawesome-free/js/conflict-detection.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free/js/conflict-detection'>;
}
declare module '@fortawesome/fontawesome-free/js/conflict-detection.min.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free/js/conflict-detection.min'>;
}
declare module '@fortawesome/fontawesome-free/js/fontawesome.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free/js/fontawesome'>;
}
declare module '@fortawesome/fontawesome-free/js/fontawesome.min.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free/js/fontawesome.min'>;
}
declare module '@fortawesome/fontawesome-free/js/regular.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free/js/regular'>;
}
declare module '@fortawesome/fontawesome-free/js/regular.min.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free/js/regular.min'>;
}
declare module '@fortawesome/fontawesome-free/js/solid.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free/js/solid'>;
}
declare module '@fortawesome/fontawesome-free/js/solid.min.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free/js/solid.min'>;
}
declare module '@fortawesome/fontawesome-free/js/v4-shims.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free/js/v4-shims'>;
}
declare module '@fortawesome/fontawesome-free/js/v4-shims.min.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free/js/v4-shims.min'>;
}
