"api_token_env": CROWDIN_PERSONAL_TOKEN
"base_path": "."
"preserve_hierarchy": true
"project_id_env": CROWDIN_PROJECT_ID

"files": [
  {
    "dest": "messages.json",
    "source": "/_locales/en/messages.json",
    "translation": "/FOOBAR/%locale_with_underscore%/baz.json"
  }
]
