"api_token_env": CROWDIN_PERSONAL_TOKEN
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
"project_id_env": CROWDIN_PROJECT_ID

"files":
  [
    {
      "dest": "messages.json",
      "source": "/_locales/en/messages.json",
      "translation": "/_locales/%two_letters_code%/%original_file_name%",
    },
  ]
