// flow-typed signature: d3b0888febc98dc246428a0c2b84fb9d
// flow-typed version: <<STUB>>/color-hash_v^1.0.3/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'color-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'color-hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'color-hash/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'color-hash/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'color-hash/dist/color-hash' {
  declare module.exports: any;
}

declare module 'color-hash/lib/bkdr-hash' {
  declare module.exports: any;
}

declare module 'color-hash/lib/color-hash' {
  declare module.exports: any;
}

declare module 'color-hash/test/bkdr-hash' {
  declare module.exports: any;
}

declare module 'color-hash/test/color-convert' {
  declare module.exports: any;
}

declare module 'color-hash/test/color-hash' {
  declare module.exports: any;
}

// Filename aliases
declare module 'color-hash/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'color-hash/coverage/lcov-report/prettify'>;
}
declare module 'color-hash/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'color-hash/coverage/lcov-report/sorter'>;
}
declare module 'color-hash/dist/color-hash.js' {
  declare module.exports: $Exports<'color-hash/dist/color-hash'>;
}
declare module 'color-hash/lib/bkdr-hash.js' {
  declare module.exports: $Exports<'color-hash/lib/bkdr-hash'>;
}
declare module 'color-hash/lib/color-hash.js' {
  declare module.exports: $Exports<'color-hash/lib/color-hash'>;
}
declare module 'color-hash/test/bkdr-hash.js' {
  declare module.exports: $Exports<'color-hash/test/bkdr-hash'>;
}
declare module 'color-hash/test/color-convert.js' {
  declare module.exports: $Exports<'color-hash/test/color-convert'>;
}
declare module 'color-hash/test/color-hash.js' {
  declare module.exports: $Exports<'color-hash/test/color-hash'>;
}
