// flow-typed signature: f0e93c5e3d96a267dbae6910d63278a0
// flow-typed version: <<STUB>>/color-hash_v^2.0.0/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'color-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'color-hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'color-hash/dist/bundle' {
  declare module.exports: any;
}

declare module 'color-hash/dist/color-hash' {
  declare module.exports: any;
}

declare module 'color-hash/dist/esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'color-hash/dist/bundle.js' {
  declare module.exports: $Exports<'color-hash/dist/bundle'>;
}
declare module 'color-hash/dist/color-hash.js' {
  declare module.exports: $Exports<'color-hash/dist/color-hash'>;
}
declare module 'color-hash/dist/esm.js' {
  declare module.exports: $Exports<'color-hash/dist/esm'>;
}
