// flow-typed signature: 07698ff8fb853737e9c965061137cdad
// flow-typed version: <<STUB>>/crowdin-api_v^4.0.0/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crowdin-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'crowdin-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'crowdin-api/index' {
  declare module.exports: $Exports<'crowdin-api'>;
}
declare module 'crowdin-api/index.js' {
  declare module.exports: $Exports<'crowdin-api'>;
}
