// flow-typed signature: 4ee686bffc9d4d4ec0d33d40d02f0c8f
// flow-typed version: <<STUB>>/flow-interfaces-chrome_v^0.4.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-interfaces-chrome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-interfaces-chrome' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-interfaces-chrome/interfaces/accessibilityFeatures' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/alarms' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/bookmarks' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/browserAction' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/browsingData' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/certificateProvider' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/Chrome' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/commands' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/contextMenus' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/cookies' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/debugger' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/desktopCapture' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/devtools' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/documentScan' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/downloads' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/events' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/extension' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/extensionTypes' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/fileBrowserHandler' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/fontSettings' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/i18n' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/idle' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/instanceID' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/networking' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/notifications' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/omnibox' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/pageAction' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/permissions' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/power' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/privacy' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/runtime' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/sessions' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/signedInDevices' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/storage' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/system' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/tabs' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/topSites' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/types' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/wallpaper' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/webstore' {
  declare module.exports: any;
}

declare module 'flow-interfaces-chrome/interfaces/windows' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-interfaces-chrome/interfaces/accessibilityFeatures.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/accessibilityFeatures'>;
}
declare module 'flow-interfaces-chrome/interfaces/alarms.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/alarms'>;
}
declare module 'flow-interfaces-chrome/interfaces/bookmarks.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/bookmarks'>;
}
declare module 'flow-interfaces-chrome/interfaces/browserAction.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/browserAction'>;
}
declare module 'flow-interfaces-chrome/interfaces/browsingData.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/browsingData'>;
}
declare module 'flow-interfaces-chrome/interfaces/certificateProvider.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/certificateProvider'>;
}
declare module 'flow-interfaces-chrome/interfaces/Chrome.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/Chrome'>;
}
declare module 'flow-interfaces-chrome/interfaces/commands.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/commands'>;
}
declare module 'flow-interfaces-chrome/interfaces/contextMenus.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/contextMenus'>;
}
declare module 'flow-interfaces-chrome/interfaces/cookies.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/cookies'>;
}
declare module 'flow-interfaces-chrome/interfaces/debugger.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/debugger'>;
}
declare module 'flow-interfaces-chrome/interfaces/desktopCapture.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/desktopCapture'>;
}
declare module 'flow-interfaces-chrome/interfaces/devtools.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/devtools'>;
}
declare module 'flow-interfaces-chrome/interfaces/documentScan.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/documentScan'>;
}
declare module 'flow-interfaces-chrome/interfaces/downloads.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/downloads'>;
}
declare module 'flow-interfaces-chrome/interfaces/events.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/events'>;
}
declare module 'flow-interfaces-chrome/interfaces/extension.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/extension'>;
}
declare module 'flow-interfaces-chrome/interfaces/extensionTypes.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/extensionTypes'>;
}
declare module 'flow-interfaces-chrome/interfaces/fileBrowserHandler.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/fileBrowserHandler'>;
}
declare module 'flow-interfaces-chrome/interfaces/fontSettings.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/fontSettings'>;
}
declare module 'flow-interfaces-chrome/interfaces/i18n.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/i18n'>;
}
declare module 'flow-interfaces-chrome/interfaces/idle.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/idle'>;
}
declare module 'flow-interfaces-chrome/interfaces/instanceID.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/instanceID'>;
}
declare module 'flow-interfaces-chrome/interfaces/networking.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/networking'>;
}
declare module 'flow-interfaces-chrome/interfaces/notifications.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/notifications'>;
}
declare module 'flow-interfaces-chrome/interfaces/omnibox.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/omnibox'>;
}
declare module 'flow-interfaces-chrome/interfaces/pageAction.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/pageAction'>;
}
declare module 'flow-interfaces-chrome/interfaces/permissions.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/permissions'>;
}
declare module 'flow-interfaces-chrome/interfaces/power.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/power'>;
}
declare module 'flow-interfaces-chrome/interfaces/privacy.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/privacy'>;
}
declare module 'flow-interfaces-chrome/interfaces/runtime.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/runtime'>;
}
declare module 'flow-interfaces-chrome/interfaces/sessions.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/sessions'>;
}
declare module 'flow-interfaces-chrome/interfaces/signedInDevices.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/signedInDevices'>;
}
declare module 'flow-interfaces-chrome/interfaces/storage.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/storage'>;
}
declare module 'flow-interfaces-chrome/interfaces/system.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/system'>;
}
declare module 'flow-interfaces-chrome/interfaces/tabs.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/tabs'>;
}
declare module 'flow-interfaces-chrome/interfaces/topSites.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/topSites'>;
}
declare module 'flow-interfaces-chrome/interfaces/types.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/types'>;
}
declare module 'flow-interfaces-chrome/interfaces/wallpaper.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/wallpaper'>;
}
declare module 'flow-interfaces-chrome/interfaces/webstore.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/webstore'>;
}
declare module 'flow-interfaces-chrome/interfaces/windows.js' {
  declare module.exports: $Exports<'flow-interfaces-chrome/interfaces/windows'>;
}
