// flow-typed signature: 1ba9185f9a374125820df2e769e22fec
// flow-typed version: <<STUB>>/gulp-eslint_v^6.0.0/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-eslint/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-eslint/index' {
  declare module.exports: $Exports<'gulp-eslint'>;
}
declare module 'gulp-eslint/index.js' {
  declare module.exports: $Exports<'gulp-eslint'>;
}
declare module 'gulp-eslint/util.js' {
  declare module.exports: $Exports<'gulp-eslint/util'>;
}
