// flow-typed signature: 36b677d73d13b1723fc03b15347aa440
// flow-typed version: <<STUB>>/gulp-json-transform_v^0.4.5/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-json-transform'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-json-transform' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-json-transform/index' {
  declare module.exports: $Exports<'gulp-json-transform'>;
}
declare module 'gulp-json-transform/index.js' {
  declare module.exports: $Exports<'gulp-json-transform'>;
}
