// flow-typed signature: fc285311de0d053008cfedb2214ed213
// flow-typed version: <<STUB>>/gulp-jest_v^3.0.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-jest/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-jest/lib/index.js' {
  declare module.exports: $Exports<'gulp-jest/lib/index'>;
}
