// flow-typed signature: 3a0693f3957e8c9279d94687c7d5fc87
// flow-typed version: <<STUB>>/gulp-unzip_v^1.1.0/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-unzip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-unzip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-unzip/index' {
  declare module.exports: $Exports<'gulp-unzip'>;
}
declare module 'gulp-unzip/index.js' {
  declare module.exports: $Exports<'gulp-unzip'>;
}
