// flow-typed signature: 2ba0fafe495a70e339793aed48ee4e1d
// flow-typed version: <<STUB>>/gulp-ignore_v^3.0.0/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-ignore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-ignore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-ignore/index' {
  declare module.exports: $Exports<'gulp-ignore'>;
}
declare module 'gulp-ignore/index.js' {
  declare module.exports: $Exports<'gulp-ignore'>;
}
