// flow-typed signature: 13b95d4360dbbde2d90120191f056939
// flow-typed version: <<STUB>>/gulp-jest_v^4.0.2/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-jest/fixture-coverage/Model-fail-test' {
  declare module.exports: any;
}

declare module 'gulp-jest/fixture-coverage/Model-pass-test' {
  declare module.exports: any;
}

declare module 'gulp-jest/fixture-coverage/Model' {
  declare module.exports: any;
}

declare module 'gulp-jest/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-jest/fixture-coverage/Model-fail-test.js' {
  declare module.exports: $Exports<'gulp-jest/fixture-coverage/Model-fail-test'>;
}
declare module 'gulp-jest/fixture-coverage/Model-pass-test.js' {
  declare module.exports: $Exports<'gulp-jest/fixture-coverage/Model-pass-test'>;
}
declare module 'gulp-jest/fixture-coverage/Model.js' {
  declare module.exports: $Exports<'gulp-jest/fixture-coverage/Model'>;
}
declare module 'gulp-jest/lib/index' {
  declare module.exports: $Exports<'gulp-jest/lib'>;
}
declare module 'gulp-jest/lib/index.js' {
  declare module.exports: $Exports<'gulp-jest/lib'>;
}
