// flow-typed signature: c011bb2f547540bf6cfacb00931a8c42
// flow-typed version: <<STUB>>/jest-cli_v^27.0.0/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-cli/bin/jest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/cli/args' {
  declare module.exports: any;
}

declare module 'jest-cli/build/cli' {
  declare module.exports: any;
}

declare module 'jest-cli/build' {
  declare module.exports: any;
}

declare module 'jest-cli/build/init/errors' {
  declare module.exports: any;
}

declare module 'jest-cli/build/init/generateConfigFile' {
  declare module.exports: any;
}

declare module 'jest-cli/build/init' {
  declare module.exports: any;
}

declare module 'jest-cli/build/init/modifyPackageJson' {
  declare module.exports: any;
}

declare module 'jest-cli/build/init/questions' {
  declare module.exports: any;
}

declare module 'jest-cli/build/init/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-cli/bin/jest.js' {
  declare module.exports: $Exports<'jest-cli/bin/jest'>;
}
declare module 'jest-cli/build/cli/args.js' {
  declare module.exports: $Exports<'jest-cli/build/cli/args'>;
}
declare module 'jest-cli/build/cli/index' {
  declare module.exports: $Exports<'jest-cli/build/cli'>;
}
declare module 'jest-cli/build/cli/index.js' {
  declare module.exports: $Exports<'jest-cli/build/cli'>;
}
declare module 'jest-cli/build/index' {
  declare module.exports: $Exports<'jest-cli/build'>;
}
declare module 'jest-cli/build/index.js' {
  declare module.exports: $Exports<'jest-cli/build'>;
}
declare module 'jest-cli/build/init/errors.js' {
  declare module.exports: $Exports<'jest-cli/build/init/errors'>;
}
declare module 'jest-cli/build/init/generateConfigFile.js' {
  declare module.exports: $Exports<'jest-cli/build/init/generateConfigFile'>;
}
declare module 'jest-cli/build/init/index' {
  declare module.exports: $Exports<'jest-cli/build/init'>;
}
declare module 'jest-cli/build/init/index.js' {
  declare module.exports: $Exports<'jest-cli/build/init'>;
}
declare module 'jest-cli/build/init/modifyPackageJson.js' {
  declare module.exports: $Exports<'jest-cli/build/init/modifyPackageJson'>;
}
declare module 'jest-cli/build/init/questions.js' {
  declare module.exports: $Exports<'jest-cli/build/init/questions'>;
}
declare module 'jest-cli/build/init/types.js' {
  declare module.exports: $Exports<'jest-cli/build/init/types'>;
}
