// flow-typed signature: 0b48f483818348a47db6cce2a4f5a602
// flow-typed version: <<STUB>>/jest-cli_v^24.8.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-cli/bin/jest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/cli/args' {
  declare module.exports: any;
}

declare module 'jest-cli/build/cli/index' {
  declare module.exports: any;
}

declare module 'jest-cli/build/index' {
  declare module.exports: any;
}

declare module 'jest-cli/build/init/constants' {
  declare module.exports: any;
}

declare module 'jest-cli/build/init/errors' {
  declare module.exports: any;
}

declare module 'jest-cli/build/init/generate_config_file' {
  declare module.exports: any;
}

declare module 'jest-cli/build/init/index' {
  declare module.exports: any;
}

declare module 'jest-cli/build/init/modify_package_json' {
  declare module.exports: any;
}

declare module 'jest-cli/build/init/questions' {
  declare module.exports: any;
}

declare module 'jest-cli/build/init/types' {
  declare module.exports: any;
}

declare module 'jest-cli/build/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-cli/bin/jest.js' {
  declare module.exports: $Exports<'jest-cli/bin/jest'>;
}
declare module 'jest-cli/build/cli/args.js' {
  declare module.exports: $Exports<'jest-cli/build/cli/args'>;
}
declare module 'jest-cli/build/cli/index.js' {
  declare module.exports: $Exports<'jest-cli/build/cli/index'>;
}
declare module 'jest-cli/build/index.js' {
  declare module.exports: $Exports<'jest-cli/build/index'>;
}
declare module 'jest-cli/build/init/constants.js' {
  declare module.exports: $Exports<'jest-cli/build/init/constants'>;
}
declare module 'jest-cli/build/init/errors.js' {
  declare module.exports: $Exports<'jest-cli/build/init/errors'>;
}
declare module 'jest-cli/build/init/generate_config_file.js' {
  declare module.exports: $Exports<'jest-cli/build/init/generate_config_file'>;
}
declare module 'jest-cli/build/init/index.js' {
  declare module.exports: $Exports<'jest-cli/build/init/index'>;
}
declare module 'jest-cli/build/init/modify_package_json.js' {
  declare module.exports: $Exports<'jest-cli/build/init/modify_package_json'>;
}
declare module 'jest-cli/build/init/questions.js' {
  declare module.exports: $Exports<'jest-cli/build/init/questions'>;
}
declare module 'jest-cli/build/init/types.js' {
  declare module.exports: $Exports<'jest-cli/build/init/types'>;
}
declare module 'jest-cli/build/version.js' {
  declare module.exports: $Exports<'jest-cli/build/version'>;
}
