// flow-typed signature: 9046c50e5010c24e0d96fac0e98ea0eb
// flow-typed version: <<STUB>>/mini-css-extract-plugin_v^0.8.0/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mini-css-extract-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mini-css-extract-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mini-css-extract-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'mini-css-extract-plugin/dist/hmr/hotModuleReplacement' {
  declare module.exports: any;
}

declare module 'mini-css-extract-plugin/dist' {
  declare module.exports: any;
}

declare module 'mini-css-extract-plugin/dist/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mini-css-extract-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'mini-css-extract-plugin/dist/cjs'>;
}
declare module 'mini-css-extract-plugin/dist/hmr/hotModuleReplacement.js' {
  declare module.exports: $Exports<'mini-css-extract-plugin/dist/hmr/hotModuleReplacement'>;
}
declare module 'mini-css-extract-plugin/dist/index' {
  declare module.exports: $Exports<'mini-css-extract-plugin/dist'>;
}
declare module 'mini-css-extract-plugin/dist/index.js' {
  declare module.exports: $Exports<'mini-css-extract-plugin/dist'>;
}
declare module 'mini-css-extract-plugin/dist/loader.js' {
  declare module.exports: $Exports<'mini-css-extract-plugin/dist/loader'>;
}
