// flow-typed signature: 116f4c78c06f775fd48bcde5f8a86e15
// flow-typed version: <<STUB>>/mini-css-extract-plugin_v^1.0.0/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mini-css-extract-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mini-css-extract-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mini-css-extract-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'mini-css-extract-plugin/dist/hmr/hotModuleReplacement' {
  declare module.exports: any;
}

declare module 'mini-css-extract-plugin/dist/hmr/normalize-url' {
  declare module.exports: any;
}

declare module 'mini-css-extract-plugin/dist' {
  declare module.exports: any;
}

declare module 'mini-css-extract-plugin/dist/loader' {
  declare module.exports: any;
}

declare module 'mini-css-extract-plugin/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mini-css-extract-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'mini-css-extract-plugin/dist/cjs'>;
}
declare module 'mini-css-extract-plugin/dist/hmr/hotModuleReplacement.js' {
  declare module.exports: $Exports<'mini-css-extract-plugin/dist/hmr/hotModuleReplacement'>;
}
declare module 'mini-css-extract-plugin/dist/hmr/normalize-url.js' {
  declare module.exports: $Exports<'mini-css-extract-plugin/dist/hmr/normalize-url'>;
}
declare module 'mini-css-extract-plugin/dist/index' {
  declare module.exports: $Exports<'mini-css-extract-plugin/dist'>;
}
declare module 'mini-css-extract-plugin/dist/index.js' {
  declare module.exports: $Exports<'mini-css-extract-plugin/dist'>;
}
declare module 'mini-css-extract-plugin/dist/loader.js' {
  declare module.exports: $Exports<'mini-css-extract-plugin/dist/loader'>;
}
declare module 'mini-css-extract-plugin/dist/utils.js' {
  declare module.exports: $Exports<'mini-css-extract-plugin/dist/utils'>;
}
