// flow-typed signature: e9f9c865f419d81d1df3521e5c8ffe14
// flow-typed version: <<STUB>>/parcel_v^2.3.2/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parcel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parcel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parcel/lib/bin' {
  declare module.exports: any;
}

declare module 'parcel/lib/cli' {
  declare module.exports: any;
}

declare module 'parcel/src/bin' {
  declare module.exports: any;
}

declare module 'parcel/src/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parcel/lib/bin.js' {
  declare module.exports: $Exports<'parcel/lib/bin'>;
}
declare module 'parcel/lib/cli.js' {
  declare module.exports: $Exports<'parcel/lib/cli'>;
}
declare module 'parcel/src/bin.js' {
  declare module.exports: $Exports<'parcel/src/bin'>;
}
declare module 'parcel/src/cli.js' {
  declare module.exports: $Exports<'parcel/src/cli'>;
}
