// flow-typed signature: 3697bf468d1097ab294c27802077d40d
// flow-typed version: <<STUB>>/react-sticky_v^6.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sticky'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sticky' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sticky/lib/Container' {
  declare module.exports: any;
}

declare module 'react-sticky/lib/index' {
  declare module.exports: any;
}

declare module 'react-sticky/lib/Sticky' {
  declare module.exports: any;
}

declare module 'react-sticky/test/setup' {
  declare module.exports: any;
}

declare module 'react-sticky/test/spec/Container' {
  declare module.exports: any;
}

declare module 'react-sticky/test/spec/Sticky' {
  declare module.exports: any;
}

declare module 'react-sticky/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sticky/lib/Container.js' {
  declare module.exports: $Exports<'react-sticky/lib/Container'>;
}
declare module 'react-sticky/lib/index.js' {
  declare module.exports: $Exports<'react-sticky/lib/index'>;
}
declare module 'react-sticky/lib/Sticky.js' {
  declare module.exports: $Exports<'react-sticky/lib/Sticky'>;
}
declare module 'react-sticky/test/setup.js' {
  declare module.exports: $Exports<'react-sticky/test/setup'>;
}
declare module 'react-sticky/test/spec/Container.js' {
  declare module.exports: $Exports<'react-sticky/test/spec/Container'>;
}
declare module 'react-sticky/test/spec/Sticky.js' {
  declare module.exports: $Exports<'react-sticky/test/spec/Sticky'>;
}
declare module 'react-sticky/webpack.config.js' {
  declare module.exports: $Exports<'react-sticky/webpack.config'>;
}
