// flow-typed signature: 3f1086785ee7b8c35c3ec226c1a22773
// flow-typed version: <<STUB>>/redux-persist-webextension-storage_v^1.0.0/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist-webextension-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist-webextension-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist-webextension-storage/dist/createStorage' {
  declare module.exports: any;
}

declare module 'redux-persist-webextension-storage/dist' {
  declare module.exports: any;
}

declare module 'redux-persist-webextension-storage/dist/localStorage' {
  declare module.exports: any;
}

declare module 'redux-persist-webextension-storage/dist/syncStorage' {
  declare module.exports: any;
}

declare module 'redux-persist-webextension-storage/prettier.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist-webextension-storage/dist/createStorage.js' {
  declare module.exports: $Exports<'redux-persist-webextension-storage/dist/createStorage'>;
}
declare module 'redux-persist-webextension-storage/dist/index' {
  declare module.exports: $Exports<'redux-persist-webextension-storage/dist'>;
}
declare module 'redux-persist-webextension-storage/dist/index.js' {
  declare module.exports: $Exports<'redux-persist-webextension-storage/dist'>;
}
declare module 'redux-persist-webextension-storage/dist/localStorage.js' {
  declare module.exports: $Exports<'redux-persist-webextension-storage/dist/localStorage'>;
}
declare module 'redux-persist-webextension-storage/dist/syncStorage.js' {
  declare module.exports: $Exports<'redux-persist-webextension-storage/dist/syncStorage'>;
}
declare module 'redux-persist-webextension-storage/prettier.config.js' {
  declare module.exports: $Exports<'redux-persist-webextension-storage/prettier.config'>;
}
