// flow-typed signature: 92b6f0e0a2b15ceba9a7584bac3e2ed1
// flow-typed version: <<STUB>>/sass_v^1.49.9/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sass/sass.dart' {
  declare module.exports: any;
}

declare module 'sass/sass.default.dart' {
  declare module.exports: any;
}

declare module 'sass/sass' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sass/sass.dart.js' {
  declare module.exports: $Exports<'sass/sass.dart'>;
}
declare module 'sass/sass.default.dart.js' {
  declare module.exports: $Exports<'sass/sass.default.dart'>;
}
declare module 'sass/sass.js' {
  declare module.exports: $Exports<'sass/sass'>;
}
