// flow-typed signature: dda2ac7a14b2bfbfaab9e3af1ebe4c03
// flow-typed version: <<STUB>>/sass-loader_v^8.0.0/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sass-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'sass-loader/dist/getDefaultSassImplementation' {
  declare module.exports: any;
}

declare module 'sass-loader/dist/getRenderFunctionFromSassImplementation' {
  declare module.exports: any;
}

declare module 'sass-loader/dist/getSassImplementation' {
  declare module.exports: any;
}

declare module 'sass-loader/dist/getSassOptions' {
  declare module.exports: any;
}

declare module 'sass-loader/dist/importsToResolve' {
  declare module.exports: any;
}

declare module 'sass-loader/dist' {
  declare module.exports: any;
}

declare module 'sass-loader/dist/proxyCustomImporters' {
  declare module.exports: any;
}

declare module 'sass-loader/dist/SassError' {
  declare module.exports: any;
}

declare module 'sass-loader/dist/webpackImporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sass-loader/dist/cjs.js' {
  declare module.exports: $Exports<'sass-loader/dist/cjs'>;
}
declare module 'sass-loader/dist/getDefaultSassImplementation.js' {
  declare module.exports: $Exports<'sass-loader/dist/getDefaultSassImplementation'>;
}
declare module 'sass-loader/dist/getRenderFunctionFromSassImplementation.js' {
  declare module.exports: $Exports<'sass-loader/dist/getRenderFunctionFromSassImplementation'>;
}
declare module 'sass-loader/dist/getSassImplementation.js' {
  declare module.exports: $Exports<'sass-loader/dist/getSassImplementation'>;
}
declare module 'sass-loader/dist/getSassOptions.js' {
  declare module.exports: $Exports<'sass-loader/dist/getSassOptions'>;
}
declare module 'sass-loader/dist/importsToResolve.js' {
  declare module.exports: $Exports<'sass-loader/dist/importsToResolve'>;
}
declare module 'sass-loader/dist/index' {
  declare module.exports: $Exports<'sass-loader/dist'>;
}
declare module 'sass-loader/dist/index.js' {
  declare module.exports: $Exports<'sass-loader/dist'>;
}
declare module 'sass-loader/dist/proxyCustomImporters.js' {
  declare module.exports: $Exports<'sass-loader/dist/proxyCustomImporters'>;
}
declare module 'sass-loader/dist/SassError.js' {
  declare module.exports: $Exports<'sass-loader/dist/SassError'>;
}
declare module 'sass-loader/dist/webpackImporter.js' {
  declare module.exports: $Exports<'sass-loader/dist/webpackImporter'>;
}
