// flow-typed signature: 381579045e149f27982be7f58306c2bb
// flow-typed version: <<STUB>>/timeago.js_v^4.0.0/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timeago.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'timeago.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'timeago.js/dist/timeago.full.min' {
  declare module.exports: any;
}

declare module 'timeago.js/dist/timeago.min' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/format' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/full' {
  declare module.exports: any;
}

declare module 'timeago.js/esm' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/interface' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/ar' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/be' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/bg' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/bn_IN' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/ca' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/cs' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/da' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/de' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/el' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/en_short' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/en_US' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/es' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/eu' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/fa' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/fi' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/fr' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/gl' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/he' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/hi_IN' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/hu' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/id_ID' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/it' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/ja' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/ka' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/ko' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/ml' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/my' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/nb_NO' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/nl' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/nn_NO' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/oc' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/pl' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/pt_BR' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/ro' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/ru' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/sq' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/sr' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/sv' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/ta' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/th' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/tr' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/uk' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/vi' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/zh_CN' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/lang/zh_TW' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/realtime' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/register' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/utils/date' {
  declare module.exports: any;
}

declare module 'timeago.js/esm/utils/dom' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/format' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/full' {
  declare module.exports: any;
}

declare module 'timeago.js/lib' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/interface' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/ar' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/be' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/bg' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/bn_IN' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/ca' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/cs' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/da' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/de' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/el' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/en_short' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/en_US' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/es' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/eu' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/fa' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/fi' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/fr' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/gl' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/he' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/hi_IN' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/hu' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/id_ID' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/it' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/ja' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/ka' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/ko' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/ml' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/my' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/nb_NO' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/nl' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/nn_NO' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/oc' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/pl' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/pt_BR' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/ro' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/ru' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/sq' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/sr' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/sv' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/ta' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/th' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/tr' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/uk' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/vi' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/zh_CN' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/lang/zh_TW' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/realtime' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/register' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/utils/date' {
  declare module.exports: any;
}

declare module 'timeago.js/lib/utils/dom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'timeago.js/dist/timeago.full.min.js' {
  declare module.exports: $Exports<'timeago.js/dist/timeago.full.min'>;
}
declare module 'timeago.js/dist/timeago.min.js' {
  declare module.exports: $Exports<'timeago.js/dist/timeago.min'>;
}
declare module 'timeago.js/esm/format.js' {
  declare module.exports: $Exports<'timeago.js/esm/format'>;
}
declare module 'timeago.js/esm/full.js' {
  declare module.exports: $Exports<'timeago.js/esm/full'>;
}
declare module 'timeago.js/esm/index' {
  declare module.exports: $Exports<'timeago.js/esm'>;
}
declare module 'timeago.js/esm/index.js' {
  declare module.exports: $Exports<'timeago.js/esm'>;
}
declare module 'timeago.js/esm/interface.js' {
  declare module.exports: $Exports<'timeago.js/esm/interface'>;
}
declare module 'timeago.js/esm/lang/ar.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/ar'>;
}
declare module 'timeago.js/esm/lang/be.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/be'>;
}
declare module 'timeago.js/esm/lang/bg.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/bg'>;
}
declare module 'timeago.js/esm/lang/bn_IN.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/bn_IN'>;
}
declare module 'timeago.js/esm/lang/ca.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/ca'>;
}
declare module 'timeago.js/esm/lang/cs.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/cs'>;
}
declare module 'timeago.js/esm/lang/da.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/da'>;
}
declare module 'timeago.js/esm/lang/de.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/de'>;
}
declare module 'timeago.js/esm/lang/el.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/el'>;
}
declare module 'timeago.js/esm/lang/en_short.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/en_short'>;
}
declare module 'timeago.js/esm/lang/en_US.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/en_US'>;
}
declare module 'timeago.js/esm/lang/es.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/es'>;
}
declare module 'timeago.js/esm/lang/eu.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/eu'>;
}
declare module 'timeago.js/esm/lang/fa.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/fa'>;
}
declare module 'timeago.js/esm/lang/fi.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/fi'>;
}
declare module 'timeago.js/esm/lang/fr.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/fr'>;
}
declare module 'timeago.js/esm/lang/gl.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/gl'>;
}
declare module 'timeago.js/esm/lang/he.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/he'>;
}
declare module 'timeago.js/esm/lang/hi_IN.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/hi_IN'>;
}
declare module 'timeago.js/esm/lang/hu.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/hu'>;
}
declare module 'timeago.js/esm/lang/id_ID.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/id_ID'>;
}
declare module 'timeago.js/esm/lang/index' {
  declare module.exports: $Exports<'timeago.js/esm/lang'>;
}
declare module 'timeago.js/esm/lang/index.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang'>;
}
declare module 'timeago.js/esm/lang/it.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/it'>;
}
declare module 'timeago.js/esm/lang/ja.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/ja'>;
}
declare module 'timeago.js/esm/lang/ka.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/ka'>;
}
declare module 'timeago.js/esm/lang/ko.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/ko'>;
}
declare module 'timeago.js/esm/lang/ml.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/ml'>;
}
declare module 'timeago.js/esm/lang/my.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/my'>;
}
declare module 'timeago.js/esm/lang/nb_NO.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/nb_NO'>;
}
declare module 'timeago.js/esm/lang/nl.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/nl'>;
}
declare module 'timeago.js/esm/lang/nn_NO.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/nn_NO'>;
}
declare module 'timeago.js/esm/lang/oc.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/oc'>;
}
declare module 'timeago.js/esm/lang/pl.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/pl'>;
}
declare module 'timeago.js/esm/lang/pt_BR.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/pt_BR'>;
}
declare module 'timeago.js/esm/lang/ro.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/ro'>;
}
declare module 'timeago.js/esm/lang/ru.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/ru'>;
}
declare module 'timeago.js/esm/lang/sq.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/sq'>;
}
declare module 'timeago.js/esm/lang/sr.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/sr'>;
}
declare module 'timeago.js/esm/lang/sv.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/sv'>;
}
declare module 'timeago.js/esm/lang/ta.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/ta'>;
}
declare module 'timeago.js/esm/lang/th.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/th'>;
}
declare module 'timeago.js/esm/lang/tr.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/tr'>;
}
declare module 'timeago.js/esm/lang/uk.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/uk'>;
}
declare module 'timeago.js/esm/lang/vi.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/vi'>;
}
declare module 'timeago.js/esm/lang/zh_CN.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/zh_CN'>;
}
declare module 'timeago.js/esm/lang/zh_TW.js' {
  declare module.exports: $Exports<'timeago.js/esm/lang/zh_TW'>;
}
declare module 'timeago.js/esm/realtime.js' {
  declare module.exports: $Exports<'timeago.js/esm/realtime'>;
}
declare module 'timeago.js/esm/register.js' {
  declare module.exports: $Exports<'timeago.js/esm/register'>;
}
declare module 'timeago.js/esm/utils/date.js' {
  declare module.exports: $Exports<'timeago.js/esm/utils/date'>;
}
declare module 'timeago.js/esm/utils/dom.js' {
  declare module.exports: $Exports<'timeago.js/esm/utils/dom'>;
}
declare module 'timeago.js/lib/format.js' {
  declare module.exports: $Exports<'timeago.js/lib/format'>;
}
declare module 'timeago.js/lib/full.js' {
  declare module.exports: $Exports<'timeago.js/lib/full'>;
}
declare module 'timeago.js/lib/index' {
  declare module.exports: $Exports<'timeago.js/lib'>;
}
declare module 'timeago.js/lib/index.js' {
  declare module.exports: $Exports<'timeago.js/lib'>;
}
declare module 'timeago.js/lib/interface.js' {
  declare module.exports: $Exports<'timeago.js/lib/interface'>;
}
declare module 'timeago.js/lib/lang/ar.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/ar'>;
}
declare module 'timeago.js/lib/lang/be.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/be'>;
}
declare module 'timeago.js/lib/lang/bg.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/bg'>;
}
declare module 'timeago.js/lib/lang/bn_IN.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/bn_IN'>;
}
declare module 'timeago.js/lib/lang/ca.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/ca'>;
}
declare module 'timeago.js/lib/lang/cs.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/cs'>;
}
declare module 'timeago.js/lib/lang/da.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/da'>;
}
declare module 'timeago.js/lib/lang/de.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/de'>;
}
declare module 'timeago.js/lib/lang/el.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/el'>;
}
declare module 'timeago.js/lib/lang/en_short.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/en_short'>;
}
declare module 'timeago.js/lib/lang/en_US.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/en_US'>;
}
declare module 'timeago.js/lib/lang/es.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/es'>;
}
declare module 'timeago.js/lib/lang/eu.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/eu'>;
}
declare module 'timeago.js/lib/lang/fa.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/fa'>;
}
declare module 'timeago.js/lib/lang/fi.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/fi'>;
}
declare module 'timeago.js/lib/lang/fr.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/fr'>;
}
declare module 'timeago.js/lib/lang/gl.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/gl'>;
}
declare module 'timeago.js/lib/lang/he.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/he'>;
}
declare module 'timeago.js/lib/lang/hi_IN.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/hi_IN'>;
}
declare module 'timeago.js/lib/lang/hu.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/hu'>;
}
declare module 'timeago.js/lib/lang/id_ID.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/id_ID'>;
}
declare module 'timeago.js/lib/lang/index' {
  declare module.exports: $Exports<'timeago.js/lib/lang'>;
}
declare module 'timeago.js/lib/lang/index.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang'>;
}
declare module 'timeago.js/lib/lang/it.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/it'>;
}
declare module 'timeago.js/lib/lang/ja.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/ja'>;
}
declare module 'timeago.js/lib/lang/ka.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/ka'>;
}
declare module 'timeago.js/lib/lang/ko.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/ko'>;
}
declare module 'timeago.js/lib/lang/ml.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/ml'>;
}
declare module 'timeago.js/lib/lang/my.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/my'>;
}
declare module 'timeago.js/lib/lang/nb_NO.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/nb_NO'>;
}
declare module 'timeago.js/lib/lang/nl.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/nl'>;
}
declare module 'timeago.js/lib/lang/nn_NO.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/nn_NO'>;
}
declare module 'timeago.js/lib/lang/oc.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/oc'>;
}
declare module 'timeago.js/lib/lang/pl.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/pl'>;
}
declare module 'timeago.js/lib/lang/pt_BR.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/pt_BR'>;
}
declare module 'timeago.js/lib/lang/ro.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/ro'>;
}
declare module 'timeago.js/lib/lang/ru.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/ru'>;
}
declare module 'timeago.js/lib/lang/sq.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/sq'>;
}
declare module 'timeago.js/lib/lang/sr.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/sr'>;
}
declare module 'timeago.js/lib/lang/sv.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/sv'>;
}
declare module 'timeago.js/lib/lang/ta.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/ta'>;
}
declare module 'timeago.js/lib/lang/th.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/th'>;
}
declare module 'timeago.js/lib/lang/tr.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/tr'>;
}
declare module 'timeago.js/lib/lang/uk.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/uk'>;
}
declare module 'timeago.js/lib/lang/vi.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/vi'>;
}
declare module 'timeago.js/lib/lang/zh_CN.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/zh_CN'>;
}
declare module 'timeago.js/lib/lang/zh_TW.js' {
  declare module.exports: $Exports<'timeago.js/lib/lang/zh_TW'>;
}
declare module 'timeago.js/lib/realtime.js' {
  declare module.exports: $Exports<'timeago.js/lib/realtime'>;
}
declare module 'timeago.js/lib/register.js' {
  declare module.exports: $Exports<'timeago.js/lib/register'>;
}
declare module 'timeago.js/lib/utils/date.js' {
  declare module.exports: $Exports<'timeago.js/lib/utils/date'>;
}
declare module 'timeago.js/lib/utils/dom.js' {
  declare module.exports: $Exports<'timeago.js/lib/utils/dom'>;
}
