// flow-typed signature: 4b1a3c7e509b32117c8bbedd4f6c96fb
// flow-typed version: <<STUB>>/timeago-react_v^2.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timeago-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'timeago-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'timeago-react/demo/demo' {
  declare module.exports: any;
}

declare module 'timeago-react/demo/dist/bundle' {
  declare module.exports: any;
}

declare module 'timeago-react/demo/timeagoComponent' {
  declare module.exports: any;
}

declare module 'timeago-react/lib/timeago-react' {
  declare module.exports: any;
}

declare module 'timeago-react/src/timeago-react' {
  declare module.exports: any;
}

declare module 'timeago-react/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'timeago-react/demo/demo.jsx' {
  declare module.exports: $Exports<'timeago-react/demo/demo'>;
}
declare module 'timeago-react/demo/dist/bundle.js' {
  declare module.exports: $Exports<'timeago-react/demo/dist/bundle'>;
}
declare module 'timeago-react/demo/timeagoComponent.jsx' {
  declare module.exports: $Exports<'timeago-react/demo/timeagoComponent'>;
}
declare module 'timeago-react/lib/timeago-react.js' {
  declare module.exports: $Exports<'timeago-react/lib/timeago-react'>;
}
declare module 'timeago-react/src/timeago-react.js' {
  declare module.exports: $Exports<'timeago-react/src/timeago-react'>;
}
declare module 'timeago-react/webpack.config.js' {
  declare module.exports: $Exports<'timeago-react/webpack.config'>;
}
