// flow-typed signature: 57f2da66d575f67fb7f42617a3c1eeec
// flow-typed version: <<STUB>>/timeago-react_v^3.0.0/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timeago-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'timeago-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'timeago-react/esm/timeago-react' {
  declare module.exports: any;
}

declare module 'timeago-react/lib/timeago-react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'timeago-react/esm/timeago-react.js' {
  declare module.exports: $Exports<'timeago-react/esm/timeago-react'>;
}
declare module 'timeago-react/lib/timeago-react.js' {
  declare module.exports: $Exports<'timeago-react/lib/timeago-react'>;
}
