// flow-typed signature: f95ce8fc8a44d06f39f9ab8eea237b50
// flow-typed version: <<STUB>>/timeago.js_v^3.0.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timeago.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'timeago.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'timeago.js/demo/index' {
  declare module.exports: any;
}

declare module 'timeago.js/dist/timeago' {
  declare module.exports: any;
}

declare module 'timeago.js/dist/timeago.locales.min' {
  declare module.exports: any;
}

declare module 'timeago.js/dist/timeago.min' {
  declare module.exports: any;
}

declare module 'timeago.js/gulpfile' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/ar' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/be' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/bg' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/ca' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/da' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/de' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/el' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/en_short' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/en' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/es' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/eu' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/fa' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/fi' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/fr' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/he' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/hu' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/in_BG' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/in_HI' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/in_ID' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/it' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/ja' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/ko' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/locales' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/ml' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/my' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/nb_NO' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/nl' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/nn_NO' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/pl' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/pt_BR' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/ro' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/ru' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/sv' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/ta' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/th' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/tr' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/uk' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/vi' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/zh_CN' {
  declare module.exports: any;
}

declare module 'timeago.js/locales/zh_TW' {
  declare module.exports: any;
}

declare module 'timeago.js/src/timeago' {
  declare module.exports: any;
}

declare module 'timeago.js/src/timeago.locales' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales_test' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/ar' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/be' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/bg' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/ca' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/en_short' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/en' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/eu' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/fa' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/fi' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/he' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/in_BG' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/in_HI' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/in_ID' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/ja' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/ko' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/my' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/nb_NO' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/nn_NO' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/pl' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/ro' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/ru' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/ta' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/tr' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/uk' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/vi' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/locales/zh_CN' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/test_dev' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/test-builder' {
  declare module.exports: any;
}

declare module 'timeago.js/tests/test' {
  declare module.exports: any;
}

declare module 'timeago.js/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'timeago.js/demo/index.js' {
  declare module.exports: $Exports<'timeago.js/demo/index'>;
}
declare module 'timeago.js/dist/timeago.js' {
  declare module.exports: $Exports<'timeago.js/dist/timeago'>;
}
declare module 'timeago.js/dist/timeago.locales.min.js' {
  declare module.exports: $Exports<'timeago.js/dist/timeago.locales.min'>;
}
declare module 'timeago.js/dist/timeago.min.js' {
  declare module.exports: $Exports<'timeago.js/dist/timeago.min'>;
}
declare module 'timeago.js/gulpfile.js' {
  declare module.exports: $Exports<'timeago.js/gulpfile'>;
}
declare module 'timeago.js/locales/ar.js' {
  declare module.exports: $Exports<'timeago.js/locales/ar'>;
}
declare module 'timeago.js/locales/be.js' {
  declare module.exports: $Exports<'timeago.js/locales/be'>;
}
declare module 'timeago.js/locales/bg.js' {
  declare module.exports: $Exports<'timeago.js/locales/bg'>;
}
declare module 'timeago.js/locales/ca.js' {
  declare module.exports: $Exports<'timeago.js/locales/ca'>;
}
declare module 'timeago.js/locales/da.js' {
  declare module.exports: $Exports<'timeago.js/locales/da'>;
}
declare module 'timeago.js/locales/de.js' {
  declare module.exports: $Exports<'timeago.js/locales/de'>;
}
declare module 'timeago.js/locales/el.js' {
  declare module.exports: $Exports<'timeago.js/locales/el'>;
}
declare module 'timeago.js/locales/en_short.js' {
  declare module.exports: $Exports<'timeago.js/locales/en_short'>;
}
declare module 'timeago.js/locales/en.js' {
  declare module.exports: $Exports<'timeago.js/locales/en'>;
}
declare module 'timeago.js/locales/es.js' {
  declare module.exports: $Exports<'timeago.js/locales/es'>;
}
declare module 'timeago.js/locales/eu.js' {
  declare module.exports: $Exports<'timeago.js/locales/eu'>;
}
declare module 'timeago.js/locales/fa.js' {
  declare module.exports: $Exports<'timeago.js/locales/fa'>;
}
declare module 'timeago.js/locales/fi.js' {
  declare module.exports: $Exports<'timeago.js/locales/fi'>;
}
declare module 'timeago.js/locales/fr.js' {
  declare module.exports: $Exports<'timeago.js/locales/fr'>;
}
declare module 'timeago.js/locales/he.js' {
  declare module.exports: $Exports<'timeago.js/locales/he'>;
}
declare module 'timeago.js/locales/hu.js' {
  declare module.exports: $Exports<'timeago.js/locales/hu'>;
}
declare module 'timeago.js/locales/in_BG.js' {
  declare module.exports: $Exports<'timeago.js/locales/in_BG'>;
}
declare module 'timeago.js/locales/in_HI.js' {
  declare module.exports: $Exports<'timeago.js/locales/in_HI'>;
}
declare module 'timeago.js/locales/in_ID.js' {
  declare module.exports: $Exports<'timeago.js/locales/in_ID'>;
}
declare module 'timeago.js/locales/it.js' {
  declare module.exports: $Exports<'timeago.js/locales/it'>;
}
declare module 'timeago.js/locales/ja.js' {
  declare module.exports: $Exports<'timeago.js/locales/ja'>;
}
declare module 'timeago.js/locales/ko.js' {
  declare module.exports: $Exports<'timeago.js/locales/ko'>;
}
declare module 'timeago.js/locales/locales.js' {
  declare module.exports: $Exports<'timeago.js/locales/locales'>;
}
declare module 'timeago.js/locales/ml.js' {
  declare module.exports: $Exports<'timeago.js/locales/ml'>;
}
declare module 'timeago.js/locales/my.js' {
  declare module.exports: $Exports<'timeago.js/locales/my'>;
}
declare module 'timeago.js/locales/nb_NO.js' {
  declare module.exports: $Exports<'timeago.js/locales/nb_NO'>;
}
declare module 'timeago.js/locales/nl.js' {
  declare module.exports: $Exports<'timeago.js/locales/nl'>;
}
declare module 'timeago.js/locales/nn_NO.js' {
  declare module.exports: $Exports<'timeago.js/locales/nn_NO'>;
}
declare module 'timeago.js/locales/pl.js' {
  declare module.exports: $Exports<'timeago.js/locales/pl'>;
}
declare module 'timeago.js/locales/pt_BR.js' {
  declare module.exports: $Exports<'timeago.js/locales/pt_BR'>;
}
declare module 'timeago.js/locales/ro.js' {
  declare module.exports: $Exports<'timeago.js/locales/ro'>;
}
declare module 'timeago.js/locales/ru.js' {
  declare module.exports: $Exports<'timeago.js/locales/ru'>;
}
declare module 'timeago.js/locales/sv.js' {
  declare module.exports: $Exports<'timeago.js/locales/sv'>;
}
declare module 'timeago.js/locales/ta.js' {
  declare module.exports: $Exports<'timeago.js/locales/ta'>;
}
declare module 'timeago.js/locales/th.js' {
  declare module.exports: $Exports<'timeago.js/locales/th'>;
}
declare module 'timeago.js/locales/tr.js' {
  declare module.exports: $Exports<'timeago.js/locales/tr'>;
}
declare module 'timeago.js/locales/uk.js' {
  declare module.exports: $Exports<'timeago.js/locales/uk'>;
}
declare module 'timeago.js/locales/vi.js' {
  declare module.exports: $Exports<'timeago.js/locales/vi'>;
}
declare module 'timeago.js/locales/zh_CN.js' {
  declare module.exports: $Exports<'timeago.js/locales/zh_CN'>;
}
declare module 'timeago.js/locales/zh_TW.js' {
  declare module.exports: $Exports<'timeago.js/locales/zh_TW'>;
}
declare module 'timeago.js/src/timeago.js' {
  declare module.exports: $Exports<'timeago.js/src/timeago'>;
}
declare module 'timeago.js/src/timeago.locales.js' {
  declare module.exports: $Exports<'timeago.js/src/timeago.locales'>;
}
declare module 'timeago.js/tests/locales_test.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales_test'>;
}
declare module 'timeago.js/tests/locales/ar.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/ar'>;
}
declare module 'timeago.js/tests/locales/be.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/be'>;
}
declare module 'timeago.js/tests/locales/bg.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/bg'>;
}
declare module 'timeago.js/tests/locales/ca.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/ca'>;
}
declare module 'timeago.js/tests/locales/en_short.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/en_short'>;
}
declare module 'timeago.js/tests/locales/en.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/en'>;
}
declare module 'timeago.js/tests/locales/eu.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/eu'>;
}
declare module 'timeago.js/tests/locales/fa.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/fa'>;
}
declare module 'timeago.js/tests/locales/fi.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/fi'>;
}
declare module 'timeago.js/tests/locales/he.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/he'>;
}
declare module 'timeago.js/tests/locales/in_BG.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/in_BG'>;
}
declare module 'timeago.js/tests/locales/in_HI.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/in_HI'>;
}
declare module 'timeago.js/tests/locales/in_ID.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/in_ID'>;
}
declare module 'timeago.js/tests/locales/ja.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/ja'>;
}
declare module 'timeago.js/tests/locales/ko.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/ko'>;
}
declare module 'timeago.js/tests/locales/my.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/my'>;
}
declare module 'timeago.js/tests/locales/nb_NO.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/nb_NO'>;
}
declare module 'timeago.js/tests/locales/nn_NO.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/nn_NO'>;
}
declare module 'timeago.js/tests/locales/pl.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/pl'>;
}
declare module 'timeago.js/tests/locales/ro.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/ro'>;
}
declare module 'timeago.js/tests/locales/ru.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/ru'>;
}
declare module 'timeago.js/tests/locales/ta.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/ta'>;
}
declare module 'timeago.js/tests/locales/tr.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/tr'>;
}
declare module 'timeago.js/tests/locales/uk.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/uk'>;
}
declare module 'timeago.js/tests/locales/vi.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/vi'>;
}
declare module 'timeago.js/tests/locales/zh_CN.js' {
  declare module.exports: $Exports<'timeago.js/tests/locales/zh_CN'>;
}
declare module 'timeago.js/tests/test_dev.js' {
  declare module.exports: $Exports<'timeago.js/tests/test_dev'>;
}
declare module 'timeago.js/tests/test-builder.js' {
  declare module.exports: $Exports<'timeago.js/tests/test-builder'>;
}
declare module 'timeago.js/tests/test.js' {
  declare module.exports: $Exports<'timeago.js/tests/test'>;
}
declare module 'timeago.js/webpack.config.js' {
  declare module.exports: $Exports<'timeago.js/webpack.config'>;
}
