// flow-typed signature: e4d264729b1c617c6481c1aeccb10f22
// flow-typed version: <<STUB>>/webpack-archive-plugin_v^3.0.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-archive-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-archive-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-archive-plugin/index' {
  declare module.exports: $Exports<'webpack-archive-plugin'>;
}
declare module 'webpack-archive-plugin/index.js' {
  declare module.exports: $Exports<'webpack-archive-plugin'>;
}
