// flow-typed signature: 7640818045f7cc46e851cdbf88f48c09
// flow-typed version: <<STUB>>/@parcel/babel-preset-env_v^2.3.2/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@parcel/babel-preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@parcel/babel-preset-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@parcel/babel-preset-env/lib' {
  declare module.exports: any;
}

declare module '@parcel/babel-preset-env/src' {
  declare module.exports: any;
}

declare module '@parcel/babel-preset-env/test/preset-env.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@parcel/babel-preset-env/lib/index' {
  declare module.exports: $Exports<'@parcel/babel-preset-env/lib'>;
}
declare module '@parcel/babel-preset-env/lib/index.js' {
  declare module.exports: $Exports<'@parcel/babel-preset-env/lib'>;
}
declare module '@parcel/babel-preset-env/src/index' {
  declare module.exports: $Exports<'@parcel/babel-preset-env/src'>;
}
declare module '@parcel/babel-preset-env/src/index.js' {
  declare module.exports: $Exports<'@parcel/babel-preset-env/src'>;
}
declare module '@parcel/babel-preset-env/test/preset-env.test.js' {
  declare module.exports: $Exports<'@parcel/babel-preset-env/test/preset-env.test'>;
}
