// flow-typed signature: 2a210084580b00754d7aa18236ca1f3f
// flow-typed version: <<STUB>>/@parcel/config-webextension_v^2.3.2/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@parcel/config-webextension'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@parcel/config-webextension' {
  declare module.exports: any;
}
