// flow-typed signature: a214797648005cc27f2e073a8deed6b9
// flow-typed version: <<STUB>>/@parcel/transformer-sass_v2.3.2/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@parcel/transformer-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@parcel/transformer-sass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@parcel/transformer-sass/lib/SassTransformer' {
  declare module.exports: any;
}

declare module '@parcel/transformer-sass/src/SassTransformer' {
  declare module.exports: any;
}

// Filename aliases
declare module '@parcel/transformer-sass/lib/SassTransformer.js' {
  declare module.exports: $Exports<'@parcel/transformer-sass/lib/SassTransformer'>;
}
declare module '@parcel/transformer-sass/src/SassTransformer.js' {
  declare module.exports: $Exports<'@parcel/transformer-sass/src/SassTransformer'>;
}
